language: python
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.3
      env: TOX_ENV=py33
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - coverage erase
  - tox -e $TOX_ENV
